---
# Use Ubuntu 'trusty' distribution
sudo: required
dist: trusty

language: php

php:
  - 5.6
  - 7.0
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  # Install recent docker
  - >
    curl -sSL "https://get.docker.com/gpg" |
     sudo -E apt-key add -
  - >
    echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" |
     sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - >
    sudo apt-get -o Dpkg::Options::="--force-confdef" \
     -o Dpkg::Options::="--force-confold" --assume-yes install docker-engine
  - sudo pip install docker-compose
  # Download selenium
  - mkdir -p selenium
  - >
    wget -c -O selenium/selenium-server-standalone-2.53.0.jar \
     http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar
  # Install NPM, Grunt, Bower, Sass
  - sudo apt-get --assume-yes install npm ruby-sass
  - sudo npm install -g bower
  - sudo npm install -g grunt-cli
  # Pull in external code dependencies, build front-end code
  - composer install
  - npm install
  - bower install
  - grunt

before_script:
  # Start selenium
  - >
    /usr/bin/xvfb-run \
     java -jar selenium/selenium-server-standalone-2.53.0.jar > selenium.log &
  # Start container
  - docker-compose up --build -d

script:
  - php vendor/bin/phpcs -n --standard=psr2 cli/ server/ test/ includes/ *.php
  - php vendor/bin/phpunit test/unit/ --coverage-text
  - php vendor/bin/phpunit test/selenium/

after_script:
  - docker-compose down

after_failure:
  - cat selenium.log

cache:
  directories:
  - selenium
...

